import React from 'react'
import LandingHeader from './LandingHeader'
import LandingFooter from './LandingFooter'

const TermsCondition = () => {
  return (
    <div>
        <LandingHeader></LandingHeader>
       <section id="landingPricing" class="section-py bg-body landing-pricing">
      <div class="container bg-icon-left position-relative ">
        <h3 class="h3 ">Terms & Conditions</h3>
        <h6>INTRODUCTION</h6>
        <p>www.quantbotsecurities.com (“we,” “us,” or “our”) welcomes you. We provide you access to our product and services through our “Website” (defined below) subject to the subsequent Terms of Service, which can be updated by us from time to time with or unexpectedly to you. By accessing and using this Website, you acknowledge that you just have read, understood and comply with be lawfully bound by these terms and conditions and our Privacy Policy, which are hereby incorporated by reference (collectively, this “Agreement”). Just in case you are doing not consider any of those terms, then please don't use the website.</p>
        
        <h6>DEFINITIONS</h6>
        <p>“Agreement” denotes to the current Terms and Conditions and also the Privacy Policy and other documents provided to you by the Website;<br />
        “Vehicle” is that the vehicle and/or vehicles matching the outline and specification as displayed from time to time on our website;<br />
        “Service” or “Services” denotes any service shown below, which we may offer from our Website;<br />
        “User”, “You” and “your” denotes to the one who is accessing the website for taking or availing any service from us;<br />
        “We”, “us” and “our” are references to QUANTBOTSECURITIES;<br />
        "Website" shall mean and include "https://quantbotsecurities.com, and any successor Website or any of its affiliates;</p>
        
        <h6>INTERPRETATION</h6>
        <p>All references to the singular include the plural and contrariwise and therefore the word "includes" should be construed as "without limitation".<br />
        Words used herein irrespective of the quantity and gender specifically used, shall be deemed and construed to incorporate the other number, singular or plural, and the other gender, masculine, feminine or neuter, because the context requires.<br />
        Reference to any statute, ordinance or other law includes all regulations and other instruments and every a consolidation , amendments, re-enactments or replacements for the nonce in effect.<br />
        All headings, bold typing and italics (if any) are inserted for convenience of reference only and don't define limit or affect the meaning or interpretation of the terms of this Agreement.<br /></p>
        
        <h6>SERVICES</h6>
        <p>Quantbotsecurities is straightforward and technical Bot for Stock & Crypto Trading. Quantbotsecurities supported Indian NSE , BSE, MCX, OPTION, FUTURE, BITCOIN, and CRYPTO. We are always working to form it More Enhance. We are providing automation Trading Most famous Broker like Fyers , Aliceblue , Samco , Upstox , and Zerodha . You'll be able to Trade any Segment, like NSE , BSE, MCX, FUTURE, OPTION with fully and Semi. Automation. You'll Apply Any Indicator on Trading view Chart & add Alerts and luxuriate in automation Trading.</p>
        
        <h6>MODIFICATIONS TO THE SERVICE</h6>
        <p>We reserve the correct, in our discretion, to change, modify, add to, or remove portions of the Terms (collectively, “Changes”), at any time. We may notify you of changes by sending an email to the address identified in your Account or by posting a Holy Scripture of the Terms incorporating the changes to its Website.</p>
        
        <h6>GEOGRAPHIC RESTRICTION</h6>
        <p>We reserve the correct to limit the usage or supply of any product or service to someone, geographical region or jurisdiction. We may use this right as per the requirement. We reserve the correct to suspend any Service at any time. Any offer to supply any Product or Service made on this Website is invalid where banned.</p>
        
        <h6>USER RESPONSIBILITIES</h6>
        
        <p>• You shall use the Service and Website for a lawful purpose and fits all the applicable laws while using the Website; • You shall not upload, any content on the website that: o Defamatory, infringes any trademark, copyright or any proprietary rights of any individual or affect anyone's privacy, contain violence or hate speech, including any sensitive information about a person. • You shall not use or access the website for collecting any research for a few competing businesses ; • You shall not misrepresent or personae somebody or entity for any false or illegal purpose; • You shall not use any virus, hacking tool for interfering within the operation of the website or data and files of the Website; • You will not use any device, scraper or any automated thing to access the website for any purpose without taking permission from us. • You will inform us about anything is inappropriate otherwise you can inform us if you discover something illegal within the website; • You will not interfere with or attempt to interrupt the correct operation of the website through the utilization of any virus, device, information collection or mechanism, software or routine, or access or attempt to gain access to any data, files, or passwords connected to the website through hacking, password or data processing, or the other means; • User must not use the Quantbotsecurities.com Website for illegal, unlawful or prohibited purposes. This includes sending or posting electronic mail or spam, publishing misleading, defamatory, indecent, obscene or advertising material, or send viruses and worms. • Users must not impersonate the other person or entity or use an assumed name or a reputation that they need no authority to use. • You will not cover, obscure, block, or in any way interfere with any advertisements and/or safety features (e.g., report abuse button) on the Website; • You will not take any action that levies or may levy (in our sole decision) an unreasonable or unreasonably big load on our technical arrangement; and • You will allow us to understand unsuitable content of which you become aware. If you discover something that infringes any law, please allow us to know, and we’ll review it. We reserve the proper, in our sole and absolute discretion, to deny you access to the website or any service, or any portion of the website or service, out of the blue, and to get rid of any content.</p>
        
        <h6>SUBSCRIPTION PLAN AND PAYMENT</h6>
        
        <p>• Any order for subscribing any Subscription plan by the User available on the website is between User and Quantbotsecurities. User comply with take particular care when providing us with its details and warrant that these details are accurate and complete at the time of ordering • SUBSCRIPTION CHARGES: it's agreed by the user that: • The User shall pay the desired subscription fee to us as per the Subscription plan available on the website . • Subscription Payment: Payment mode shall be: Online: Credit Cards and Debit cards; • Any order for subscribing to any Subscription plan that you simply place with us is subject to acceptance by us. Once you place your order online we'll email you to substantiate that we've got received it. • We may refuse or be unable to process your order/subscription if: • Your card doesn't give authorization for the payment of price. • You do not meet the eligibility to order criteria kicked off above. • The user can cancel the subscription of any service anytime through contacting us. • No refund shall be applicable on the paid service. For any issue you'll be able to contact us through email: support@quantbotsecurities.com • We take customer feedback very seriously and use it to constantly improve our products and quality of service.</p>
        
        <h6>GENERAL CONDITIONS</h6>
        
        <p>• We don't guarantee the accuracy, completeness, validity, or timeliness of data listed by us. • We make material changes to those terms and conditions from time to time, we may notify you either by prominently posting a notice of such changes or via email communication. • The website is licensed to you on a limited, non-exclusive, non-transferrable, non-sub-licensable basis, solely to be utilized in reference to the Service for your private, personal, non-commercial use, subject to all or any the terms and conditions of this Agreement as they're applicable to the Service. • You further acknowledge and agree that we've got no obligation whatsoever to furnish any maintenance and support services with relevance the website.</p>
        
        <h6>RELEASE</h6>
        
        <p>You release us and our successors from all losses, damages, rights, and demands and actions of any kind, including personal injuries, death, and property damage, that are directly or indirectly associated with or arising from your use of the Services (collectively, “Claims”).</p>
        
        <h6>EXCLUSION OF LIABILITY</h6>
        
        <p>You understand and agree that we (a) don't guarantee the accuracy, completeness, validity, or timeliness of knowledge listed by us or provided by us or any third parties; and (b) shall not be answerable for any materials posted by us or provided by us or any third party. You shall use your own judgment, caution, and customary sense in evaluating any prospective methods or offers and any information provided by us or any third party. Further, we shall not be accountable for direct, indirect consequential or the other sort of loss or damage that will be suffered by a user through the employment of the www.quantbotsecurities.com Website including loss of knowledge or information or any quite financial or physical loss or damage. In no event shall QUANTBOTSECURITIES, nor its Owners, directors, employees, partners, agents, suppliers, or affiliates, be in control of any indirect, incidental, special, eventful or exemplary costs, including without limitation, loss of proceeds, figures, usage, goodwill, or other intangible losses, consequential from (i) your use or access of or failure to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content attained from the Service; and (iv) unlawful access, use or alteration of your transmissions or content, whether supported guarantee, agreement, domestic wrong (including carelessness) or the other lawful concept, whether we've been responsive to the likelihood of such damage, and whether a cure set forth herein is originated to own futile of its important purpose.</p>
        
        <h6>NO RESPONSIBILITY</h6>
        
        <p>• We aren't responsible to you for: • any reliance that you simply may place on any material or commentary posted on our website. Please note that nothing contained in our website or the fabric published on that is meant to amount to advice on which you must rely; or • any losses you suffer because the knowledge you set into our website is inaccurate or incomplete; or • any losses you suffer if the data you set into our website is accurate but the Service provider's website has not accurately reflected that information because its system isn't working correctly; or • any losses you suffer if you misrepresent any fact which can influence the Service provider’s decision to simply accept the danger or the terms offered; or • any losses you suffer because you can't use our website at any time; or • any errors in or omissions from our website; or • any unauthorized access or loss of non-public information that's beyond our control.</p>
        
        <h6>THIRD PARTY LINKS</h6>
        
        <p>The Website may comprise links to external or third-party Websites (“External Sites”). These links are provided exclusively as ease to you and not as an authorization by us of the content on such External Sites. The content of such External Sites is formed and utilized by others. You'll be able to communicate the location administrator of these External Sites. We don't seem to be in control of the content provided within the link of any External Sites and don't provide any representations about the content or correctness of the data on such External Sites. You ought to take safety measure(s) once you are downloading files from of these Websites to safeguard your computer from viruses and other critical programs. If you conform to access linked External Sites, you are doing so at your own risk.</p>
        
        <h6>PERSONAL INFORMATION AND PRIVACY POLICY</h6>
        
        <p>By accessing or using this Website, you approve us to use, store or otherwise process your personal information as per our Privacy Policy.</p>
        
        <h6>ERRORS, INACCURACIES AND OMISSIONS</h6>
        <p>Every effort has been taken to make sure that the knowledge offered on this Website is accurate and error-free. We apologize for any errors or omissions which will have occurred. We cannot offer you any warranty that usage of the website are error-free or fit purpose, timely, that defects are going to be amended, or that the positioning or the server that produces it available are freed from viruses or bugs or signifies the complete functionality, accuracy, reliability of the website and that we don't make any warranty whatsoever, whether express or implied, referring to fitness for purpose, or accuracy.</p>
        
        <h6>DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</h6>
        <p>THE WEBSITE and therefore the SERVICE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS with none WARRANTIES OF ANY KIND, INCLUDING THAT the website WILL OPERATE ERROR-FREE OR THAT the website , ITS SERVERS OR ITS CONTENT OR SERVICE ARE freed from COMPUTER VIRUSES OR SIMILAR CONTAMINATION OR DESTRUCTIVE FEATURES. WE DISCLAIM ALL LICENSES OR WARRANTIES, INCLUDING, BUT NOT LIMITED TO, LICENSES OR WARRANTIES OF TITLE, MERCHANTABILITY, NON-VIOLATION OF THIRD PARTIES’ RIGHTS, AND FITNESS FOR PARTICULAR PURPOSE AND ANY WARRANTIES ARISING FROM A MATTER OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. IN RELATION WITH ANY WARRANTY, CONTRACT, OR COMMON LAW TORT CLAIMS: (I) WE SHALL NOT BE to blame for ANY UNINTENDED, INCIDENTAL, OR SUBSTANTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS STOPPAGE RESULTING FROM the utilization OR INABILITY TO ACCESS AND USE the website OR THE CONTENT, whether we've got BEEN RECOMMENDED OF the chance OF SUCH DAMAGES. The website MAY COMPRISE TECHNICAL INCORRECTNESS OR TYPOGRAPHICAL ERRORS OR OMISSIONS. UNLESS REQUIRED BY APPLICABLE LAWS, WE don't seem to be in charge of ANY SUCH TYPOGRAPHICAL, TECHNICAL, OR PRICING ERRORS RECORDED ON the website . The website MAY CONTAIN INFORMATION ON CERTAIN SERVICES, NOT ALL OF WHICH ARE AVAILABLE IN EVERY LOCATION. A regard to A SERVICE ON THE WEBSITES doesn't SUGGEST THAT SUCH SERVICE IS OR are going to be ACCESSIBLE IN YOUR LOCATION. WE RESERVE the proper to try and do Change , CORRECTIONS, AND/OR IMPROVEMENTS TO the website AT ANY TIME all at once.</p>
        
        <h6>INDEMNIFICATION</h6>
        <p>You conform to defend, indemnify, and hold us and our officers, directors, employees, successors, licensees harmless from and against any claims, actions, or demands, including, without limitation, reasonable legal and accounting fees, arising or resulting from your breach of this Agreement or your misuse of the Content or the website . We shall provide notice to you of any such claim, suit, or proceeding and shall assist you, at your expense, in defending any such claim, suit, or proceeding. We reserve the correct, at your expense, to assume the exclusive defense and control of any matter that's subject to indemnification under this section. In such case, you comply with cooperate with any reasonable requests assisting our defense of such matter.</p>
        
        <h6>MISCELLANEOUS</h6>
        <p>SEVERABILITY If any provision of those Terms is found to be unenforceable or invalid, that provision are going to be limited or eliminated to the minimum extent necessary, so the Terms will otherwise remain fully force and effect and enforceable. TERMINATION Term. The Services are going to be provided to you'll be cancelled or terminated by us. You'll be able to terminate our services by contacting us at our email: support@quantbotsecurities.com. We may terminate these Services at any time, with or without cause, upon written notice. We are going to don't have any liability to you or any third party thanks to such termination. Termination of those Terms will terminate all of your Services subscriptions. Effect of Termination. Upon termination of those Terms for any reason, or cancellation or expiration of your Services: (a) we'll cease providing the Services; (b) you'll not be entitled to any refunds or usage fees, or the other fees, pro rata or otherwise; (c) any fees you owe to us will immediately become due and payable fully, and (d) we may delete your archived data within 30 days. All sections of the Terms that expressly provide for survival, or by their nature should survive, will survive termination of the Terms, including, without limitation, indemnification, warranty disclaimers, and limitations of liability. ENTIRE AGREEMENT This Agreement constitutes the complete agreement between the parties hereto with relevancy the topic matter contained during this Agreement. GOVERNING LAW AND JUDICIAL RECOURSE The terms herein are going to be governed by and construed in accordance with the law of India without giving effect to any principles of conflicts of law. The courts of India shall have exclusive jurisdiction over any dispute arising from the employment of the website . Act of God we'll don't have any liability to you, your users, or any third party for any failure to perform our or its obligations under these Terms within the event that such non-performance arises as results of the occurrence of a happening beyond the reasonable control people, including, without limitation, an act of war or terrorism, natural disaster, failure of electricity supply, riot, civil disorder, or civil commotion or other via major event. ASSIGNMENT We shall have the proper to assign/transfer this agreement to any third party including its company, subsidiaries, affiliates, associates and group companies, with none consent of the User. CONTACT INFORMATION If you have got any questions about these Terms, please contact us at support@quantbotsecurities.com.</p>


      </div>
    </section>
    <LandingFooter></LandingFooter>   
    </div>
  )
}

export default TermsCondition
